linkedlist:
	gcc -o ./target/linkedlist ./source/linkedlist.c ./source/linkedfunction.c -I./source

run:
	./target/linkedlist 1 4 52 5 23 3
	./target/linkedlist 5 4 3 2 1
	./target/linkedlist 52 6 2 62 52 23 52


	
	
	