main:
	gcc -o ./target/stack ./src/main.c ./src/stackfunction.c -I./src

run:
	./target/stack.exe

app:
	gcc -o 	./target/stack_application ./src/stack_application.c -I./src

test:
	./target/stack_application -f "(1 + 4 / 3)" -a